### ISSUE TITLE
Produce individual service checks

### ISSUE THREAD

**Issue by anwa-github** [halfordfan/check-mk-homeassistant#1]
The actual version returns 

```
<<<check_mk>>>
Version: 1.0
AgentOS: HomeAssistant
0 Supervisor connected=1 Supervisor reports Connected
0 Supported connected=1 Supported reports Supported
0 Healthy connected=1 Healthy reports Healthy
```

which produces an ok status for the "agent".

With 

```
21a22
>   print('<<<local>>>')
50,51c51
<   print(code + ' ' + service + perf + service + ' reports ' + nicestatus)
<
---
>   print(code + ' ' + service + ' -' + perf + service + ' reports ' + nicestatus)
```

one gets three additional services with its individual status:

```
<<<check_mk>>>
Version: 1.0
AgentOS: HomeAssistant
<<<local>>>
0 Supervisor - connected=1 Supervisor reports Connected
0 Supported - connected=1 Supported reports Supported
0 Healthy - connected=1 Healthy reports Healthy
```

[https://pasteboard.co/cTalQ0xCEvrt.png](url)

**Comment by halfordfan** [comment]
Tell me a little more about your configuration.  Are you running the CheckMK agent on the HA host as well as this local check?  Or are you running this check from the Check MK server in addition to the agent to the agent on the host?  Or no host agent, only this check?

In my configuration, I have a rule for <code>Individual program call instead of agent access</code> that uses SSH to run the agent on the HAOS VM, then runs the haobserver code with the <code>local</code> immediately after by using a semi-colon in the command line.  I get service statistics.  I must admit I have not tested other configurations.

It looks like I could make a simple change in the command line arg processing that would insert the local tag where appropriate.

**Comment by halfordfan** [comment]
Confirmed this bug.  When run without the CMK agent, the local header needs to be inserted to report service statuses.
